Repository ROSEN-A/ROSEN-Group-A, pull requests merged in 2022-09, with the labels that each got.

#13 Created Documentation folder and Research subfolder
  Documentation/Research/README.md
Labels: task

#17 Create Meeting Minute File
  Documentation/Meeting/meeting minutes.md
Labels: chores

#18 11 research on tech documentation on blender
  Documentation/Research/Blender.md
Labels: task

#19 9 research on tech documentation on active learning algorithm
  Documentation/Research/ALA.md
Labels: task

#20 Added research of Angular and D3
  Documentation/Research/Research on Development Framework.md
Labels: task

#21 Update meeting minutes
  Documentation/Meeting/meeting minutes.md
Labels: task

#24 Update readme in main
  README.md
Labels: chore

#23 Updated readme in Research
  Documentation/Research/README.md
Labels: chore

#22 Added IP agreement with our team member agreements
  Documentation/IPAgreement.pdf
Labels: chore
